name: Shopkeepers
version: '${shopkeepers.version}'
description: Custom villager shopkeepers
authors: [nisovin, blablubbabc]
website: '${shopkeepers.dbo.url}'
# Loading after world management plugins and soft dependencies:
softdepend: [Multiverse-Core, My Worlds, Transporter, Towny, WorldGuard, Citizens, Vault, Gringotts, ChestShop]
# Ensuring that our listeners run before those of some protection plugins which listen on LOWEST priority as well:
loadbefore: [GriefPrevention]

main: com.nisovin.shopkeepers.SKShopkeepersPlugin
api-version: '1.14'

commands:
    shopkeeper:
        description: Base for all shopkeeper commands.
        aliases: [shopkeepers]
        usage: 'Unknown command! Try /<command> help'

permissions:
    # Command permissions:
    shopkeeper.help:
        description: Display command help
        default: true
    shopkeeper.reload:
        description: Reload the plugin
        default: op
    shopkeeper.debug:
        description: Toggle debug mode and access debugging commands
        default: op

    shopkeeper.list.own:
        description: List your own player shops
        default: true
    shopkeeper.list.others:
        description: List the player shops of other players
        default: op
    shopkeeper.list.admin:
        description: List the admin shops
        default: op

    shopkeeper.history.own:
        description: View your own trading history
        default: true
    shopkeeper.history.all:
        description: View the trading history of everybody
        default: op
        children:
            shopkeeper.history.own: true

    shopkeeper.remove.own:
        description: Remove all your own player shops via command
        default: op
    shopkeeper.remove.others:
        description: Remove all the player shops of other players via command
        default: op
    shopkeeper.remove.all:
        description: Remove all player shops of all players at once via command
        default: op
    shopkeeper.remove.admin:
        description: Remove all admin shops via command
        default: op

    shopkeeper.give:
        description: Give shop creation items per command
        default: op
    shopkeeper.remote:
        description: Remotely open admin shops via command
        default: op
    shopkeeper.remoteedit:
        description: Remotely edit shops via command
        default: op
    shopkeeper.transfer:
        description: Transfer ownership of player shops
        default: op
    shopkeeper.settradeperm:
        description: Set the trade permissions for admin shops
        default: op
    shopkeeper.setforhire:
        description: Set a shopkeeper to be for hire
        default: op

    # General permissions
    shopkeeper.trade:
        description: Allows trading with shopkeepers
        default: true
    shopkeeper.hire:
        description: Allows hiring of shopkeepers
        default: true
    shopkeeper.bypass:
        description: Bypass player shop restrictions (access player shops of others)
        default: op
    # Dynamic max shops permissions: The default max shops limit is configured in the config.
    # shopkeeper.maxshops.<count>
    #   description: The maximum number of shops a player can have, only values setup in the config can be used
    #   default: false

    # Shop types:
    shopkeeper.admin:
        description: Create and modify admin shopkeepers
        default: op
    shopkeeper.player.sell:
        description: Create selling player shopkeepers
        default: false
    shopkeeper.player.buy:
        description: Create buying player shopkeepers
        default: false
    shopkeeper.player.trade:
        description: Create trading player shopkeepers
        default: false
    shopkeeper.player.book:
        description: Create books selling player shopkeepers
        default: false
    shopkeeper.player:
        description: Create any type of player shopkeeper
        default: true
        children:
            shopkeeper.player.sell: true
            shopkeeper.player.buy: true
            shopkeeper.player.trade: true
            shopkeeper.player.book: true

    # Shop objects:
    shopkeeper.sign:
        description: Create sign shopkeepers
        default: true
    shopkeeper.citizen:
        description: Create citizens (npc) shopkeepers
        default: op
    shopkeeper.entity.*:
        description: Create shopkeepers of any entity types
        default: op
    # Dynamic mob type permissions:
    # You can find all entity type names here:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
    # The permissions use the lower case entity type name.
    # shopkeeper.entity.<mob-type>:
    #   description: Create shopkeepers of the specified mob type
    #   default: false

    # Legacy permissions:
    shopkeeper.player.normal:
        description: Create and modify selling player shopkeepers
        default: true
        children:
            shopkeeper.player.sell: true
    shopkeeper.villager:
        description: Create villager shopkeepers
        default: true
        children:
            shopkeeper.entity.villager: true
    shopkeeper.witch:
        description: Create witch shopkeepers
        default: true
        children:
            shopkeeper.entity.witch: true
    shopkeeper.creeper:
        description: Create creeper shopkeepers
        default: true
        children:
            shopkeeper.entity.creeper: true

    # Star notation: Includes all other permissions
    shopkeeper.*:
        description: Access to everything
        default: op
        children:
            shopkeeper.help: true
            shopkeeper.reload: true
            shopkeeper.debug: true
            shopkeeper.list.own: true
            shopkeeper.list.others: true
            shopkeeper.list.admin: true
            shopkeeper.history.own: true
            shopkeeper.history.all: true
            shopkeeper.remove.own: true
            shopkeeper.remove.others: true
            shopkeeper.remove.all: true
            shopkeeper.remove.admin: true
            shopkeeper.give: true
            shopkeeper.remote: true
            shopkeeper.remoteedit: true
            shopkeeper.transfer: true
            shopkeeper.settradeperm: true
            shopkeeper.setforhire: true
            shopkeeper.hire: true
            shopkeeper.trade: true
            shopkeeper.bypass: true
            shopkeeper.admin: true
            shopkeeper.player: true
            shopkeeper.sign: true
            shopkeeper.citizen: true
            shopkeeper.entity.*: true
