ext {
	craftbukkitVersion = '26.3.build.+'
}

apply from: rootProject.file('modules/shared/nmsModulePaper.gradle')

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

java.disableAutoTargetJvm()

/*paperweight {
	javaLauncher = javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(25)
	}
}*/
